# Generated by Django 3.2 on 2021-05-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='status',
            field=models.CharField(blank=True, choices=[('Registered', 'Registered'), ('On hold', 'On hold'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Registered (expired)', 'Registered (expired)')], default='open', max_length=30),
        ),
    ]
